WIP RgbdSensor -> CameraArray: Initial high-level changes
SeanCurtis-TRI/drake pull request #5
Opened 2019-06-24 19:14 UTC by EricCousineau-TRI

- Start trending towards using `CameraInfo`
- Add initial simplified terminology treatise
- Rename `Rgbd*` to `CameraArray`
- Get rid of default transform; I personally do not want it there, as I
feel it does more harm than good (adds too much noise)

WARNING: This will not compile. This is just an initial preview.

This incorporates feedback from draft PR #11337, and will supersede it.

2019-06-24 19:18 UTC, EricCousineau-TRI reviewed
+@seancurtis-tri for initial review, please

Can you give the high-level parts a glance over, and defer grammar to once we settle on the higher-level bits?

\cc @kunimatsu-tri @thduynguyen

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Li9v4MMChi1h24ZXg_Y:bj6bdds)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-06-24 19:23 UTC, EricCousineau-TRI commented
___
*[geometry/render/camera_properties.h, line 55 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Li9wFRmEEYQI8CwdS4L:-Li9wFRmEEYQI8CwdS4M:b-9e5kuj) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/geometry/render/camera_properties.h#L55)):*
> ```objc
> };
> 
> // TODO(SeanCurtis-TRI): Add properties for structured-light depth sensor which
> ```

Er, I thought this was trending towards stereo, but completely missed the emitter / sensor part. Will restore.


<!-- Sent from Reviewable.io -->

2019-06-24 21:49 UTC, kunimatsu-tri commented
___
*[systems/sensors/camera_array.h, line 89 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiAQpHJAppeaEw4b11g:-LiAQpHJAppeaEw4b11h:b2ymiwu) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L89)):*
> ```objc
> 
>  @ingroup sensor_systems  */
> class CameraArray final : public LeafSystem<double> {
> ```

Per f2f discussion, if this class is going to be generic, I would suggest to rename it to `MultiCameraSensor`. In this case, it eventually should provide a way to construct any type and the number of cameras into this class, and users will be able to handle both normal rgb stereo and rgbd sensor through this class.

If this only refers to a sensor that outputs rgb and depth images, I vote for `RgbdSensor`.

`CameraArray` might be confusing between a sensor that has multiple cameras inside it, e.g. Intel D415, vs. a system that has multiple sensors, e.g. a system that uses multi D415.


<!-- Sent from Reviewable.io -->

2019-06-24 22:11 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kunimatsu-tri and @SeanCurtis-TRI)

___
*[systems/sensors/camera_array.h, line 89 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiAQpHJAppeaEw4b11g:-LiAXXf1ELpF1j4NULSh:b-om11up) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L89)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Per f2f discussion, if this class is going to be generic, I would suggest to rename it to `MultiCameraSensor`. In this case, it eventually should provide a way to construct any type and the number of cameras into this class, and users will be able to handle both normal rgb stereo and rgbd sensor through this class.

If this only refers to a sensor that outputs rgb and depth images, I vote for `RgbdSensor`.

`CameraArray` might be confusing between a sensor that has multiple cameras inside it, e.g. Intel D415, vs. a system that has multiple sensors, e.g. a system that uses multi D415.
</blockquote></details>

Perhaps the true solution is to call this: `SimpleRgbdSensor` (although that *does* miss out on the label images it can produce. The point I'm going for is to not have this the end all be all. But a simple stopgap to go from *not* producing images to producing images. Maybe we introduce an advanced system that is more configurable separately?

If we like that, then the only thing necessary is to make sure we use the right language.


<!-- Sent from Reviewable.io -->

2019-06-24 23:38 UTC, kunimatsu-tri commented
___
*[systems/sensors/camera_array.h, line 89 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiAQpHJAppeaEw4b11g:-LiApP2TEkS82UGHLvQp:bolq6g3) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L89)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Perhaps the true solution is to call this: `SimpleRgbdSensor` (although that *does* miss out on the label images it can produce. The point I'm going for is to not have this the end all be all. But a simple stopgap to go from *not* producing images to producing images. Maybe we introduce an advanced system that is more configurable separately?

If we like that, then the only thing necessary is to make sure we use the right language.
</blockquote></details>

By "a sensor that outputs rgb and depth images" I was assuming that a label image always comes with an rgb image.

As for `RgbdSensor` vs. `SimpleRgbdSensor`, I like `RgbdSensor` better just because it's simpler than `SimpleRgbdSensor`. lol


<!-- Sent from Reviewable.io -->

2019-06-25 18:46 UTC, SeanCurtis-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 13 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiExRuM2_JFkLB8rwOd:-LiExRuM2_JFkLB8rwOe:b-vtes0i) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L13)):*
> ```objc
> // TODO(kunimatsu-tri) Add camera distortion parameters and other parameters as
> // needed.
> /**
> ```

I'm *quite* surprised that the connection between the erstwhile `RgbdSensor` and this is *purely* rhetorical. It seems to reduce the importance of linking them in a single PR.
___
*[systems/sensors/camera_array.h, line 27 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwDwcD-O7Ol9LJjrW:-LiEwDwd53qS7bAibS2q:b-v4l17g) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L27)):*
> ```objc
> namespace sensors {
> 
> // TODO(eric.cousineau): Generalize this to be any set of cameras to
> ```

I generally wonder if you're "correcting" this class or trying to turn it into a different class. Certainly the whole concept of `CameraArray` makes me suspicious.

I really don't see the use case in abstracting this into a general array and, therefore, can't see the point in laying the groundwork into that abstraction.
___
*[systems/sensors/camera_array.h, line 49 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwbRH2Ps2LxjDFlHw:-LiEwbRH2Ps2LxjDFlHx:b-i6wg0m) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L49)):*
> ```objc
> 
>    - `W` - world frame
>    - `B` - base frame
> ```

Will these have definitions? Definitions in the sense that someone can intuitively map the name of a frame to something in the real world?  "Base" is *incredibly* generic.
___
*[systems/sensors/camera_array.h, line 171 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwx32DDJ6rWozoy2C:-LiEwx32DDJ6rWozoy2D:b-kxfxha) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L171)):*
> ```objc
>     for `X_WB`.
>    */
>   const OutputPort<double>& X_WB_output_port() const;
> ```

BTW Is this *really* a port that provides value?  @kunimatsu-tri @ericcousineau-tri
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-LiEx6Iq-oTmHpj9u7EI:bi9mo83) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
> ```objc
>   // otherwise be a perfectly represented matrix.
>   math::RigidTransformd X_BC_{
>     math::RotationMatrixd::MakeFromOrthonormalRows(
> ```

BTW I certainly like the idea of removing this and putting the burden of the creator/factory method for configuring a particular camera.
___
*[systems/sensors/rgbd_sensor.cc, line 42 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiExHzd2Exbw6XAwf4F:-LiExHzd2Exbw6XAwf4G:b-j3m8w4) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.cc#L42)):*
> ```cpp
>       properties_(properties),
>       X_PB_(X_PB) {
>   this->set_name(name);
> ```

Don't want to name cameras?


<!-- Sent from Reviewable.io -->

2019-06-25 19:38 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 13 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiExRuM2_JFkLB8rwOd:-LiF6tOG7-6mOmjjOjlG:b-pacvt6) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L13)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm *quite* surprised that the connection between the erstwhile `RgbdSensor` and this is *purely* rhetorical. It seems to reduce the importance of linking them in a single PR.
</blockquote></details>

Yes, but at some point, I'd much rather have `CameraProperties` be composed of `CameraInfo` (after it moves out of `drake/systems/...`); rationale being (a) it's being used more in Anzu, and does everything we want, and (b) `CameraProperties` leaks too many details about the `RenderEngine` API (storing only a small bit of rendering info rather than just a constraint check, storing render engine name, etc.).

Hence the TODO.
I'm also fine with encoding that TODO into a real issue; but I do want this connection to start being made.
___
*[systems/sensors/camera_array.h, line 27 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwDwcD-O7Ol9LJjrW:-LiF61plBCg4nN1hTgPB:b-1n2ihh) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I generally wonder if you're "correcting" this class or trying to turn it into a different class. Certainly the whole concept of `CameraArray` makes me suspicious.

I really don't see the use case in abstracting this into a general array and, therefore, can't see the point in laying the groundwork into that abstraction.
</blockquote></details>

Yeah, speaking with Kuni in f2f, you're both right. This admits way too much scope creep without a good design. Will remove this TODO.
___
*[systems/sensors/camera_array.h, line 89 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiAQpHJAppeaEw4b11g:-LiF6Bzh1FJoNIIxzNL_:b-n9tfry) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L89)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

By "a sensor that outputs rgb and depth images" I was assuming that a label image always comes with an rgb image.

As for `RgbdSensor` vs. `SimpleRgbdSensor`, I like `RgbdSensor` better just because it's simpler than `SimpleRgbdSensor`. lol

</blockquote></details>

I'll go back to `RgbdSensor` - much easier diff to look at!
___
*[systems/sensors/camera_array.h, line 171 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwx32DDJ6rWozoy2C:-LiF6EwqCQeU4UpZFRPd:b-7eskz6) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L171)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is this *really* a port that provides value?  @kunimatsu-tri @ericcousineau-tri
</blockquote></details>

Raising to blocking (as I'm totes in favor of having less code than more)

I personally haven't used it; it *could* be semi-useful at some point for things like usage with Katy's point cloud utilities, but I'd be down for removing it for now, and just rely on the exposure of `parent_frame_id`.

Will remove.
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-LiF6ewK1dcVOuE838qt:bia24hy) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I certainly like the idea of removing this and putting the burden of the creator/factory method for configuring a particular camera.
</blockquote></details>

Yasss!!!!
___
*[systems/sensors/rgbd_sensor.cc, line 42 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiExHzd2Exbw6XAwf4F:-LiF6gaV8RpMszcc5tww:b-95nw31) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.cc#L42)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Don't want to name cameras?
</blockquote></details>

I'd prefer not to. I'd much rather that the downstream user be responsible for it as a *system*, which is all that argument is for.

We don't set / require the name for `MultibodyPlant`, `SceneGraph`, so I don't think we really should for `RgbdSensor`.


<!-- Sent from Reviewable.io -->

2019-06-25 20:15 UTC, kunimatsu-tri commented
___
*[systems/sensors/camera_array.h, line 171 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwx32DDJ6rWozoy2C:-LiFGUD-2S_7vdtn8o0p:bm2szwi) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L171)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Raising to blocking (as I'm totes in favor of having less code than more)

I personally haven't used it; it *could* be semi-useful at some point for things like usage with Katy's point cloud utilities, but I'd be down for removing it for now, and just rely on the exposure of `parent_frame_id`.

Will remove.
</blockquote></details>

If we can keep track with at which frame images are captured using SG APIs or whatever, we don't need this anymore. If not, we need this.


<!-- Sent from Reviewable.io -->

2019-06-25 22:09 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_array.h, line 171 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwx32DDJ6rWozoy2C:-LiFfgwz7vWhLoSbhXIa:bj9uogn) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L171)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

If we can keep track with at which frame images are captured using SG APIs or whatever, we don't need this anymore. If not, we need this.
</blockquote></details>

I suspect we'll need it given frame `B`. SG can only tell you the parent frame to which `B` is affixed.  I.e., given `X_WP` and `X_PB`, `SceneGraph` owns the former and `RgbdSensor` owns the latter. So, to get `X_WB`, `RgbdSensor` has to do that composition. It's in.


<!-- Sent from Reviewable.io -->

2019-06-28 13:38 UTC, SeanCurtis-TRI requested changes
Sorry for the laggardly response. I realized I hadn't commented the actual new documentation -- the very meat that caused the previous PR to grind to a halt.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LiTIWld83LuSAZv9w2f:bd76zmr)* status: all files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI and @kunimatsu-tri)

___
*[geometry/render/camera_properties.h, line 55 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Li9wFRmEEYQI8CwdS4L:-LiTDysRCqgcJD6HnZIo:btp0tyc) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/geometry/render/camera_properties.h#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er, I thought this was trending towards stereo, but completely missed the emitter / sensor part. Will restore.
</blockquote></details>

Yeah...I had the vague understanding that we're going stereo + structured light. One of the reasons why I anticipate there will be further derivations of `CameraProperties`.
___
*[systems/sensors/camera_info.h, line 13 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiExRuM2_JFkLB8rwOd:-LiTEdzDARgCkBcP0e-R:b-j37mul) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yes, but at some point, I'd much rather have `CameraProperties` be composed of `CameraInfo` (after it moves out of `drake/systems/...`); rationale being (a) it's being used more in Anzu, and does everything we want, and (b) `CameraProperties` leaks too many details about the `RenderEngine` API (storing only a small bit of rendering info rather than just a constraint check, storing render engine name, etc.).

Hence the TODO.
I'm also fine with encoding that TODO into a real issue; but I do want this connection to start being made.
</blockquote></details>

What does "`CameraProperties` be composed of `CameraInfo`" mean? As in `CamProperties` has a `CameraInfo`? I'd be in favor of that. And renaming it to `RenderCameraProperties` at that point (I.e., layering render-specific items on top of the abstract specification of a camera.) Have I got the right flavor of what you're thinking?
___
*[systems/sensors/camera_info.h, line 19 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTF5T_09uX1GWoqPOd:-LiTF5T_09uX1GWoqPOe:b-7z5967) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L19)):*
> ```objc
> Please note the following terms:
> 
> - frame, coordinate system, pose: denotes 2D/3D spaces, as in
> ```

nit: Why both "frame" and "coordinate system"?  Also, the phrase "denotes a space" is contradictory to the documentation you link to. In fact, it doesn't seem to define a frame at all (only its constituent parts: an origin and a space-spanning basis).
___
*[systems/sensors/camera_info.h, line 21 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTFj7w-dYX6SgPMTRI:-LiTFj7w-dYX6SgPMTRJ:bqp7obk) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L21)):*
> ```objc
> - frame, coordinate system, pose: denotes 2D/3D spaces, as in
>   @ref multibody_frames_and_bodies.
> - video frame: an image in a video sequence.
> ```

Boom! And now we overload "frame". It's  space *and* an image.

If we're going to distinguish between "video frame" and all other "described frames", I would argue we should call out that overload explicitly.
___
*[systems/sensors/camera_info.h, line 22 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTFo8y5BPYA5-Xfxqf:-LiTFo8y5BPYA5-Xfxqg:b48l3vo) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L22)):*
> ```objc
>   @ref multibody_frames_and_bodies.
> - video frame: an image in a video sequence.
> - camera: an image sensor with lens; in Drake, this will be modeled as a
> ```

Camera defined in terms of "sensor" which is not defined.  

Is this the place to define Drake implementation? And is it relevant in drake that the camera aperture is a point? It's certainly not a point that is ever explicitly referred to in the API. This kind of detail doesn't seem to belong in a glossary-style piece of rhetoric.
___
*[systems/sensors/camera_info.h, line 27 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTGit78D3eC7qk-r56:-LiTGit78D3eC7qk-r57:b-7zgx5e) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L27)):*
> ```objc
> - image plane: defines how the 3D world is projected to a 2D image.
> 
> The camera frame is described as follows:
> ```

I'd recommend monogram notation:

The camera frame C comprised of the basis [Cx Cy Cz] and the origin point Co. Then you can talk about these vectors and this point being aligned with or positioned at more cleanly. FOr example

- Cz is point's in the camera's viewing direction.
___
*[systems/sensors/camera_info.h, line 30 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTGNJG2nNI6jha776z:-LiTGNJG2nNI6jha777-:b-kxf244) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L30)):*
> ```objc
> 
> - origin located at camera aperature
> - +Z-axis aligned with the optical axis along the viewing direction,
> ```

BTW optical axis is undefined. This (and the concept of viewing direction) probably go in the definition of camera. And once those are defined, just saying it's aligned with the viewing direction is enough.
___
*[systems/sensors/camera_info.h, line 32 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTH9RhBD_fPrVnB2Jc:-LiTH9RiCc2Sn4jaAKma:bcpdslz) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L32)):*
> ```objc
> - +Z-axis aligned with the optical axis along the viewing direction,
>   orthogonal to the image plane.
> - +X-axis aligned with the right direction of the image plane
> ```

We have two objects "camera" and "image plane". But now you're describing the *camera*'s frame in terms of the *image plane* without relating the two.
___
*[systems/sensors/camera_info.h, line 35 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHK9UELNwbKKm2rJY:-LiTHK9UELNwbKKm2rJZ:b-k7q8br) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L35)):*
> ```objc
> - +Y-axis aligned with the downwards direction of the image plane.
> 
> This can be summarized as `X-right`, `Y-down`, and `Z-forward`.
> ```

This summary only works with a frame of reference. Right relative to what? ETc.
___
*[systems/sensors/camera_info.h, line 37 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHPGx1YWGGXdPM6hl:-LiTHPGx1YWGGXdPM6hm:bc3ut79) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L37)):*
> ```objc
> This can be summarized as `X-right`, `Y-down`, and `Z-forward`.
> 
> The image plane can be described the following coordinate systems:
> ```

Missing a preposition...."...can be described __*with*__ the following...". Perhaps "in" would be better. That's still a bit unhappy -- because I would suggest an image plane requires more description that just frames. Instead, the image plane has properties each associated with frames.

The relationship of these frames needs to be better elaborated.
___
*[systems/sensors/camera_info.h, line 39 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHdohDsq9y47qSOJK:-LiTHdoiBSVrSOoqm4XL:bvqkli5) ([raw file](htt [...]

2019-06-28 20:46 UTC, EricCousineau-TRI reviewed
Some parts addressed, working on others.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LiUpjMK35JE4Y2as5Af:b4lpny1)* status: 0 of 6 files reviewed, 14 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 13 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiExRuM2_JFkLB8rwOd:-LiUkClq8SItpaBDr-2Y:b3l7olr) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L13)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What does "`CameraProperties` be composed of `CameraInfo`" mean? As in `CamProperties` has a `CameraInfo`? I'd be in favor of that. And renaming it to `RenderCameraProperties` at that point (I.e., layering render-specific items on top of the abstract specification of a camera.) Have I got the right flavor of what you're thinking?
</blockquote></details>

Yup! Updated TODO in `camera_properties`.
___
*[systems/sensors/camera_info.h, line 19 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTF5T_09uX1GWoqPOd:-LiUpKS19x6i9Jc3CAfi:b-44mzo9) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Why both "frame" and "coordinate system"?  Also, the phrase "denotes a space" is contradictory to the documentation you link to. In fact, it doesn't seem to define a frame at all (only its constituent parts: an origin and a space-spanning basis).
</blockquote></details>

OK Took a whack at it.
___
*[systems/sensors/camera_info.h, line 22 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTFo8y5BPYA5-Xfxqf:-LiUkPYr7do9kISvHcO-:b-kyf4hb) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Camera defined in terms of "sensor" which is not defined.  

Is this the place to define Drake implementation? And is it relevant in drake that the camera aperture is a point? It's certainly not a point that is ever explicitly referred to in the API. This kind of detail doesn't seem to belong in a glossary-style piece of rhetoric.
</blockquote></details>

I believe the definition of aperature as a point belongs here, as well as in this glossary rhetoric, since these classes are for using a pinhole camera model?
___
*[systems/sensors/camera_info.h, line 27 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTGit78D3eC7qk-r56:-LiUpWHk2JAK1OmlTiM-:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd recommend monogram notation:

The camera frame C comprised of the basis [Cx Cy Cz] and the origin point Co. Then you can talk about these vectors and this point being aligned with or positioned at more cleanly. FOr example

- Cz is point's in the camera's viewing direction.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 43 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTI27E91sUFD46D-oV:-LiUnlvG0SvzAJLqibbu:b-aosc5a) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

why `center_*` "describe the principal point rather than `principal_*`? And given you're doing math, you need to measure and express the principal point in *some* frame.

Have you also considered doing this in a more linear algebra kind of way?
</blockquote></details>

`center_` is to stay consistent with the accessors defind below. The scalar math is used to be consistent with the math of `fov` and `focal_x` down below.

While the linear algebra is useful-ish, I don't consider it to be too much of value-add in this spot?
___
*[systems/sensors/camera_array.h, line 49 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwbRH2Ps2LxjDFlHw:-LiUpaXM9S9RTNVz6fUi:boatn7c) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Will these have definitions? Definitions in the sense that someone can intuitively map the name of a frame to something in the real world?  "Base" is *incredibly* generic.
</blockquote></details>

Done. (Tried to clarify as "sensor base".)
___
*[systems/sensors/camera_array.h, line 89 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiAQpHJAppeaEw4b11g:-LiUpdW5DrGaUhQb5sU6:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'll go back to `RgbdSensor` - much easier diff to look at!
</blockquote></details>

Done.
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-LiUjx2L9Jilb6BeO3pC:bo0017h) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

On the other hand, it puts the burden on *every* caller, whether they want to pay it or not. I assume that this particular definition of `X_BC` comes from somewhere and probably should be captured.

Perhaps a number of static members that produce X_BC associated with something of import?
</blockquote></details>

I'm not sure it provides value right now.

I believe it comes from the Xtion, which is application-specific; giving that as a default, or even with easy access, may lead people to use dumb + incorrect values out of laziness. If they're incorrect, I'd prefer the incorrectness be simple.


<!-- Sent from Reviewable.io -->

2019-06-28 21:13 UTC, SeanCurtis-TRI requested changes
Continued some conversations.

> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LiUvrPw60QFK2vjSSXC:b2bq16q)* status: all files reviewed, 14 unresolved discussions (waiting on @EricCousineau-TRI and @kunimatsu-tri)

___
*[systems/sensors/camera_info.h, line 22 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTFo8y5BPYA5-Xfxqf:-LiUs4yJAep5QWE_NDLn:b-r3i1hx) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe the definition of aperature as a point belongs here, as well as in this glossary rhetoric, since these classes are for using a pinhole camera model?
</blockquote></details>

So, it's my bad for conflating two points in the same comment.  I'm going to respond to what you *responded* to and then make a separate comment for the other issue just to keep things nicely separated.

This section is purely a glossary: frame, pose, video frame, camera, image plane. Those concepts exist independently of Drake's implementation (and have nothing to do with the aperture.

If you want to define aperture and provide the relationship between camera, image sensor, and aperture, I'd be fine with that. But this *particular* glossary item does not end how it starts.
___
*[systems/sensors/camera_info.h, line 23 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiUvOHPCC7JSIcp5Gfn:-LiUvOHPCC7JSIcp5Gfo:b-bllgo4) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L23)):*
> ```objc
> - video frame: an image in a video sequence.
> - camera: an image sensor with lens; in Drake, this will be modeled as a
>   pinhole cameras unless stated otherwise. Because of this, the camera
> ```

You're going to have to do some heavy work to convince me we're modeling a pinhole camera. It's only pinhole in that we have a functionally zero aperture. But we do model focal length. (Without, in any way, touching on the subject of "exposure" as it relates to aperture). So, I'm not persuaded that pinhole camera is the right analogy.
___
*[systems/sensors/camera_info.h, line 43 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTI27E91sUFD46D-oV:-LiUt0gr6MGB0DwzTWC-:b-76q6yf) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`center_` is to stay consistent with the accessors defind below. The scalar math is used to be consistent with the math of `fov` and `focal_x` down below.

While the linear algebra is useful-ish, I don't consider it to be too much of value-add in this spot?
</blockquote></details>

I suspect any issue I might have will go away when "principal point" gets a definition.
___
*[systems/sensors/camera_info.h, line 22 at r2](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiUsJJp47B2eA6EvwgS:-LiUsJJp47B2eA6EvwgT:b-jq6ty2) ([raw file](https://github.com/seancurtis-tri/drake/blob/34a26b3ae462638425ca9c8724f47eb203da82ea/systems/sensors/camera_info.h#L22)):*
> ```objc
>   @ref multibody_frames_and_bodies.
> - video frame: an image in a video sequence.
> - camera: an image sensor with lens; in Drake, this will be modeled as a
> ```

Camera is defined as an "image sensor" but "image sensor" has no particular meaning in this document. You are relying, 100% on the reader coming to the table with that knowledge (but we're defining "frame"?) Seems inconsistent.
___
*[systems/sensors/camera_info.h, line 27 at r2](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiUsoRZ99gDym9eRxof:-LiUsoRZ99gDym9eRxog:b-qmioxt) ([raw file](https://github.com/seancurtis-tri/drake/blob/34a26b3ae462638425ca9c8724f47eb203da82ea/systems/sensors/camera_info.h#L27)):*
> ```objc
> - image plane: defines how the 3D world is projected to a 2D image.
> 
> The camera frame `C` is comprised of the basis [Cx Cy Cz] and origin point Co,
> ```

BTW You might as well omit the ticks on C as you don't have them anywhere else.
___
*[systems/sensors/camera_array.h, line 49 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEwbRH2Ps2LxjDFlHw:-LiUtA3AD2bqDt_UPmCR:bew03b5) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_array.h#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. (Tried to clarify as "sensor base".)
</blockquote></details>

Definitely an improvement. I'd suggest that the addition of "sensor" as a prefix as less value than the "used as..." clause. 

It seems there's a missing point here. I'm going to meander here. If what I say has value, I'll leave it to you to distill it.

- We have two sensor frames: color and depth.
- In an `RgbdSensor` they have a fixed relationship. 
- That relationship is defined w.r.t. a common frame B -- the base frame. Physically, the base frame represents the position of the physical container of the sensor (the "body"). The camera is posed in the world by defining `X_WB`.
- By default, because B, C, and D are all coincident and aligned, the viewing direction (as defined in `CameraInfo`) for both color and depth point in the Bz direction. (Is Bz right? I didn't stop to make sure that was correct.)

For me, there's a lot of important data in those bullets that is not successfully captured.  Your thoughts?
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-LiUuUJ108IImzBCzavh:bdbwyme) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure it provides value right now.

I believe it comes from the Xtion, which is application-specific; giving that as a default, or even with easy access, may lead people to use dumb + incorrect values out of laziness. If they're incorrect, I'd prefer the incorrectness be simple.
</blockquote></details>

I need to stop doing this to the review. I introduce two topics and one always seems to get lost.

1. I agree with your point that (stipulating those old values came from Xtion), that they don't necessarily model any other camera correctly. So, defaulting to that is not necessarily a good thing.
2. (this is the point that got lost) We should have `RgbdSensor::GetXtionX_BC()` as sugar so that a user doesn't have to generate this particular transform themselves. And current tests that rely on it can easily configure themselves into their current state -- but no longer default that way. It need not *strictly* be a static method. But we should have *some* API that allows us to easily get useful X_BC/X_BD for cameras we know we're interested in.


<!-- Sent from Reviewable.io -->

2019-06-28 21:41 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: all files reviewed, 14 unresolved discussions (waiting on @EricCousineau-TRI and @kunimatsu-tri)

___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-LiV1Es19Gbr2sLXBMuG:b-q6qzxq) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I need to stop doing this to the review. I introduce two topics and one always seems to get lost.

1. I agree with your point that (stipulating those old values came from Xtion), that they don't necessarily model any other camera correctly. So, defaulting to that is not necessarily a good thing.
2. (this is the point that got lost) We should have `RgbdSensor::GetXtionX_BC()` as sugar so that a user doesn't have to generate this particular transform themselves. And current tests that rely on it can easily configure themselves into their current state -- but no longer default that way. It need not *strictly* be a static method. But we should have *some* API that allows us to easily get useful X_BC/X_BD for cameras we know we're interested in.
</blockquote></details>

Further thought -- the sugar should actually generate an entire `RgbdCamera`, where it is responsible for creating the `CameraProperties` and the underlying `CameraInfo` that is consistent with our model of a particular physical camera.


<!-- Sent from Reviewable.io -->

2019-07-12 20:56 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 6 of 12 files reviewed, 15 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljby8jB9T5mzhlrRkn-:-Ljby8jB9T5mzhlrRkn0:b5p13zp) (no related file):*
Will try to incorporate conversation from Wed:
https://github.com/RobotLocomotion/drake/pull/11337#issuecomment-511029895 

---


<!-- Sent from Reviewable.io -->

2019-07-16 12:44 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 6 of 12 files reviewed, 15 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljby8jB9T5mzhlrRkn-:-LjunqRG1So6vN9s484Z:b-e2qsjx) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Will try to incorporate conversation from Wed:
https://github.com/RobotLocomotion/drake/pull/11337#issuecomment-511029895 
</blockquote></details>

I'm setting a deadline. Unless this merges *this* week, I'm going to push on with the main PR. I'm going to emphasize, that this must be *merged* this week. That means, even if it gets close, if it doesn't hit, I'm jettisoning it. Too much time has passed.

---


<!-- Sent from Reviewable.io -->

2019-07-16 17:52 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @kunimatsu-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljby8jB9T5mzhlrRkn-:-Ljvqdh5AQIF8x1wXcLr:bgrcewz) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm setting a deadline. Unless this merges *this* week, I'm going to push on with the main PR. I'm going to emphasize, that this must be *merged* this week. That means, even if it gets close, if it doesn't hit, I'm jettisoning it. Too much time has passed.
</blockquote></details>

That's more than generous, thank you! Working on it now.

---
___
*[systems/sensors/camera_info.h, line 21 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTFj7w-dYX6SgPMTRI:-LjvqnuNBUzLwUALmrU_:bkbiqbp) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Boom! And now we overload "frame". It's  space *and* an image.

If we're going to distinguish between "video frame" and all other "described frames", I would argue we should call out that overload explicitly.
</blockquote></details>

Done. Tried it?
___
*[systems/sensors/camera_info.h, line 22 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTFo8y5BPYA5-Xfxqf:-Ljvqyih3xGA69uFjdgX:bi4sjo9) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

So, it's my bad for conflating two points in the same comment.  I'm going to respond to what you *responded* to and then make a separate comment for the other issue just to keep things nicely separated.

This section is purely a glossary: frame, pose, video frame, camera, image plane. Those concepts exist independently of Drake's implementation (and have nothing to do with the aperture.

If you want to define aperture and provide the relationship between camera, image sensor, and aperture, I'd be fine with that. But this *particular* glossary item does not end how it starts.
</blockquote></details>

OK I am still capturing "sensor" here per our prior discussions, but I can eliminate it if it provides no value (is too general).
___
*[systems/sensors/camera_info.h, line 23 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiUvOHPCC7JSIcp5Gfn:-Ljvr4ck7C7kv3I7VSvH:bfxhbbd) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You're going to have to do some heavy work to convince me we're modeling a pinhole camera. It's only pinhole in that we have a functionally zero aperture. But we do model focal length. (Without, in any way, touching on the subject of "exposure" as it relates to aperture). So, I'm not persuaded that pinhole camera is the right analogy.
</blockquote></details>

Done. Made an initial pass of defining "pinhole  camera" vs. "pinhole model" since it came up in discussion as well.
___
*[systems/sensors/camera_info.h, line 32 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTH9RhBD_fPrVnB2Jc:-LjvrBob1t44irWdJT6p:bxxczw) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

We have two objects "camera" and "image plane". But now you're describing the *camera*'s frame in terms of the *image plane* without relating the two.
</blockquote></details>

Done. I think...
___
*[systems/sensors/camera_info.h, line 35 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHK9UELNwbKKm2rJY:-LjvuR4vEavi1BjN_wbk:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This summary only works with a frame of reference. Right relative to what? ETc.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 37 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHPGx1YWGGXdPM6hl:-LjvuF4m3v1o-6WplGBL:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L37)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Missing a preposition...."...can be described __*with*__ the following...". Perhaps "in" would be better. That's still a bit unhappy -- because I would suggest an image plane requires more description that just frames. Instead, the image plane has properties each associated with frames.

The relationship of these frames needs to be better elaborated.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 39 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHdohDsq9y47qSOJK:-LjvrN8b-B-0ONIeDwuy:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

"principal point" undefined.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 39 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHiNqBIRP2qL1cJf4:-LjvuEZ-EpGKo-HTeSIG:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Dimension of coordinate system is unclear. Also, the symbol Z is likewise unclear in this context.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 43 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTI27E91sUFD46D-oV:-LjvuKMb4Juz3Otw1iOv:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I suspect any issue I might have will go away when "principal point" gets a definition.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 22 at r2](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiUsJJp47B2eA6EvwgS:-Ljvr3TpD2IW0ZkGRZND:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/34a26b3ae462638425ca9c8724f47eb203da82ea/systems/sensors/camera_info.h#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Camera is defined as an "image sensor" but "image sensor" has no particular meaning in this document. You are relying, 100% on the reader coming to the table with that knowledge (but we're defining "frame"?) Seems inconsistent.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 37 at r4](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljvsazq9WYqSsG3eG4m:-Ljvsazr2PYOR8sw8K6K:b-5puuoi) ([raw file](https://github.com/seancurtis-tri/drake/blob/28253c01e3c3354b49002f47432eb2507c32d1a6/systems/sensors/camera_info.h#L37)):*
> ```objc
>   cameras are assumed to use the pinhole model unless otherwise stated. The
>   images captured by these cameras are 2D, and their pixel coordinates are
>   described as `(u, v)`.
> ```

I had trouble trying to stage the "camera" definition with the "pinhole camera" and "pinhole model" definitions.
Does this look OK, or should I  [...]

2019-07-16 19:11 UTC, SeanCurtis-TRI requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: all files reviewed, 22 unresolved discussions (waiting on @EricCousineau-TRI and @kunimatsu-tri)

*[a discussion](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljby8jB9T5mzhlrRkn-:-LjwBdxDEkCMVDNOKo2I:bqrn6ek) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

That's more than generous, thank you! Working on it now.
</blockquote></details>

In the spirit of getting this done -- I've done another pass.

---
___
*[systems/sensors/camera_info.h, line 32 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTH9RhBD_fPrVnB2Jc:-Ljw8hkS4OROSUw3bdlI:buby81e) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. I think...
</blockquote></details>

Not yet (see other note).
___
*[systems/sensors/camera_info.h, line 35 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHK9UELNwbKKm2rJY:-Ljw8nFv6MguOzs0ttrN:b26wzfo) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L35)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This begs for illustration. I may attempt to try writing something to see how hard it is.
___
*[systems/sensors/camera_info.h, line 43 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTI27E91sUFD46D-oV:-Ljw9XbwElPnqEv3Ve7U:bmrvlbw) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It hasn't gone way for the reason I gave -- the camera center is not synonymous with the principal point.
___
*[systems/sensors/camera_info.h, line 37 at r4](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljvsazq9WYqSsG3eG4m:-Ljw848wEcbJPUu6wAxW:bdjuiy7) ([raw file](https://github.com/seancurtis-tri/drake/blob/28253c01e3c3354b49002f47432eb2507c32d1a6/systems/sensors/camera_info.h#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I had trouble trying to stage the "camera" definition with the "pinhole camera" and "pinhole model" definitions.
Does this look OK, or should I change it?
</blockquote></details>

See other notes.
___
*[systems/sensors/camera_info.h, line 48 at r4](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LjvsoQF-yVBIMWXHmJD:-Ljw8Teu3PCGrFLJLXA9:bwchb4d) ([raw file](https://github.com/seancurtis-tri/drake/blob/28253c01e3c3354b49002f47432eb2507c32d1a6/systems/sensors/camera_info.h#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is the usage of `u` axis too implicit here? Is there a better way to introduce this?
</blockquote></details>

I'd favor something more explicit.

Also we haven't related "captured image" with any other quantity.
___
*[systems/sensors/camera_info.h, line 22 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw5GQr9Aq74WYwML-Q:-Ljw5GQr9Aq74WYwML-R:b-xrq2ur) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L22)):*
> ```objc
>   @ref multibody_frames_and_bodies. Unless otherwise stated, any described
>   frame implies this definition.
> - video frame: an image in a video sequence. This is *not* an extension of
> ```

BTW Maybe this would be better off as a footnote. By including it in this bulleted list, it gives it the weight of all of the other terms here. And that's simply not the case.
___
*[systems/sensors/camera_info.h, line 25 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw5SKT4uYoH6SiriXU:-Ljw5SKT4uYoH6SiriXV:b-8x8d4p) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L25)):*
> ```objc
>   "frame" as a general term.
> - sensor: a device used to take and report measurements.
> - image: an array of measurements. Coordinates are in pixels.
> ```

BTW Perhaps "Coordinates are __*typically*__ in pixels."
___
*[systems/sensors/camera_info.h, line 26 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw5X6VCsLdtgdBls_x:-Ljw5X6VCsLdtgdBls_y:b-mph4l1) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L26)):*
> ```objc
> - sensor: a device used to take and report measurements.
> - image: an array of measurements. Coordinates are in pixels.
> - imager: a sensor that measures images.
> ```

nit: A sensor whose measurements are reported in images. (The image *is* the measurements not the thing measured.)
___
*[systems/sensors/camera_info.h, line 27 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw6HV1-yqf2zD8WMEp:-Ljw6HV1-yqf2zD8WMEq:b-ps0viv) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L27)):*
> ```objc
> - image: an array of measurements. Coordinates are in pixels.
> - imager: a sensor that measures images.
> - camera: an image sensor.
> ```

This feels insufficient. It is true without providing distinguishing power. After all, there are image sensors that are *not* cameras (e.g., Lidar). We referenced lenses and photoreceptive surfaces in our discussion. I'm not 100% sure that's exactly the *right* characterization, but I have the gut feeling that it's close.
___
*[systems/sensors/camera_info.h, line 29 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw6nkS4mi4tJZwI-_V:-Ljw6nkS4mi4tJZwI-_W:b-grzba3) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L29)):*
> ```objc
> - camera: an image sensor.
> - aperature: a hole through which light travels through.
> - image plane: defines how the 3D world is projected to a 2D image. In
> ```

Doesn't define it. The optic mechanism (lens + aperture) does that. This merely captures the projection.
___
*[systems/sensors/camera_info.h, line 30 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw70dl7FKciZXme7FP:-Ljw70dl7FKciZXme7FQ:b-cda318) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L30)):*
> ```objc
> - aperature: a hole through which light travels through.
> - image plane: defines how the 3D world is projected to a 2D image. In
>   accordance with the OpenCV documentation below, the image plane will be
> ```

The "in front" vs "in back" should really belong to a specific discussion of a "camera model" and not the glossary of the terms.
___
*[systems/sensors/camera_info.h, line 33 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw7XrbCDUMynxtLBlr:-Ljw7Xrc4M1Zuh7FJ7Fi:b-lqz2v0) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L33)):*
> ```objc
>   presented as though it were "in front" of the aperature, rather than behind
>   (which requires accounting for the camera obscura effect).
> - pinhole camera: a physical camera with no lens and a tiny aperature.
> ```

I'd say this is where a link would go (and/or a summary of properties).
___
*[systems/sensors/camera_info.h, line 34 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw7CsG1B-SAuMACc8O:-Ljw7CsG1B-SAuMACc8P:b-qgpbp5) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L34)):*
> ``` [...]

2019-07-16 21:13 UTC, SeanCurtis-TRI reviewed
Back in your court.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LjwcVPM9oBrrWmDzYWm:b-k8t49j)* status: all files reviewed, 22 unresolved discussions (waiting on @EricCousineau-TRI and @kunimatsu-tri)



<!-- Sent from Reviewable.io -->

2019-07-16 23:31 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 5 of 6 files reviewed, 18 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 43 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTI27E91sUFD46D-oV:-Ljx6zYf8voQ1C-Q3NWu:b-ddkrdc) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It hasn't gone way for the reason I gave -- the camera center is not synonymous with the principal point.
</blockquote></details>

Done - I think?
___
*[systems/sensors/camera_info.h, line 48 at r4](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LjvsoQF-yVBIMWXHmJD:-Ljx6TRq-FUCkf_4_ZAT:b1gliql) ([raw file](https://github.com/seancurtis-tri/drake/blob/28253c01e3c3354b49002f47432eb2507c32d1a6/systems/sensors/camera_info.h#L48)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd favor something more explicit.

Also we haven't related "captured image" with any other quantity.
</blockquote></details>

I can't think of a better way to be explicit; can I ask if you have any suggestions?
___
*[systems/sensors/camera_info.h, line 27 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw6HV1-yqf2zD8WMEp:-Ljx6tVXEh2MMoYHcN53:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This feels insufficient. It is true without providing distinguishing power. After all, there are image sensors that are *not* cameras (e.g., Lidar). We referenced lenses and photoreceptive surfaces in our discussion. I'm not 100% sure that's exactly the *right* characterization, but I have the gut feeling that it's close.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 29 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw6nkS4mi4tJZwI-_V:-Ljx6hJsCw4uBhHKnihq:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Doesn't define it. The optic mechanism (lens + aperture) does that. This merely captures the projection.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 30 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw70dl7FKciZXme7FP:-Ljx6fuk2S4H9iXsyBNN:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The "in front" vs "in back" should really belong to a specific discussion of a "camera model" and not the glossary of the terms.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 33 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw7XrbCDUMynxtLBlr:-Ljx6fdq7Af-Mf9oNW3S:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L33)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd say this is where a link would go (and/or a summary of properties).
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 34 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw7nOsAlMHdKjcL_gh:-Ljx6egwDDgPGjdTU63l:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd actually advocate pulling this discussion out into its own section: "The camera model". That's where we define the model's details (2d images, uv coords, frames and their relatiohnships, etc.) Those are all artifacts of the model which inform the API.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 34 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw7CsG1B-SAuMACc8O:-Ljx6eyjCvP9wfr_5i1I:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

*This* is where the detail of the image plane would make sense. The pinhole *camera* has the image plane *behind* the optics, the model has it in front. The model's image is reversed from what the camera's image would be.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 40 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw87P417PX8ES7njVe:-Ljx6cK5CjWSSJNpQAh8:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L40)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think you could totally get away with an intuitive/colloquial elaboration. "In other words, it's the way the camera is facing."
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 41 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw8Hwp8tFZWgXLPDRH:-Ljx6bNx1beH7pgE6T3Y:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L41)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This feels controversial -- from our conversation on-site, some opinions put the "camera center" at the aperture whereas the principal point clearly lies on the image plane. Therefore, these are not names for the same point.
</blockquote></details>

Done.
___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-Ljx5CXz8Hki4-HwZjUy:b-7jyhwg) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm pretty sure this is a lie. it's not "focal length" as the name suggests, it's actually a different quantity. Focal length would be in meters giving `u` units of m⋅pixels which is not what is intended. It's actually derived from a number of quantities (to do the remapping into pixel space).
</blockquote></details>

I'd prefer that we keep this as "focal length", as both OpenCV and the MathWorks docs tend to refer to these values as "focal lengths":
https://www.mathworks.com/help/vision/ref/cameraparameters.html#d117e104857
___
*[systems/sensors/camera_info.h, line 65 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LjwA4yQD2DmYhWWV9l7:-Ljx70H47B7oF0eDaJmg:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I like a link to the OpenCV pinhole model *somewhere* -- probably as part of a section that's dedicated to the camera "model" (to which I alluded above.)
</blockquote></details>

Done.
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Ljx71p57mihkNWiKOiR:b-9ykp84) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean [...]

2019-07-16 23:32 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 5 of 6 files reviewed, 18 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Ljx7Dov0RbhzR8mpHgl:bdr1xsf) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'd almost prefer that live in test code; adding public API solely for minimizing unittests sounds like the wrong motivation?
</blockquote></details>

Er, meant "minimizing unittest changes"


<!-- Sent from Reviewable.io -->

2019-07-16 23:37 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljby8jB9T5mzhlrRkn-:-Ljx7M3JDnkeqcPIMiMr:b-alwlhs) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the spirit of getting this done -- I've done another pass.
</blockquote></details>

Pass back!

---
___
*[systems/sensors/camera_info.h, line 35 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiTHK9UELNwbKKm2rJY:-Ljx8PQC0wzaVEiaDRYx:b-og8t0b) ([raw file](https://github.com/seancurtis-tri/drake/blob/1ed7777b61c9c84c1cd4114b715bb92ec734ad58/systems/sensors/camera_info.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This begs for illustration. I may attempt to try writing something to see how hard it is.
</blockquote></details>

This coincides with the OpenCV docs; is there a way we can just leverage that?
___
*[systems/sensors/rgbd_sensor.h, line 45 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LjwAKLVEwImpH4EF0pL:-Ljx8Ejn5ucK_jkQWd2t:b-m3g1fw) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/rgbd_sensor.h#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Perhaps some further elaboration. This provides a *what* but not a *why*. E.g.:

> color camera frame, used for both color and label cameras to guarantee perfect registration between color and label images.

Probably also worth a shout-out to the `camera_info` definition of "camera frame".
</blockquote></details>

Done. (Left out reference to `camera_info`, as it was made in the sentence immediately above this paragraph.)


<!-- Sent from Reviewable.io -->

2019-07-17 00:16 UTC, SeanCurtis-TRI requested changes
One quick response on something that caught my eye. I'll have to hit the rest of it after getting my daughter fed.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LjxHImvA8g5QRnHP1ka:b3n8ln2)* status: 4 of 6 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-LjxGSXL6vPoYgJjOb6x:b-iec0rj) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'd prefer that we keep this as "focal length", as both OpenCV and the MathWorks docs tend to refer to these values as "focal lengths":
https://www.mathworks.com/help/vision/ref/cameraparameters.html#d117e104857
</blockquote></details>

That matlab documentation you link to highlights the ambiguity and confusion. A lens has *a* focal length - a measure from the center of the lens to the focal plane. In the documentation, it is referred to as `F`. But they *also* define `fx` and `fy` as "focal length in x and y". However, the units of `fx` and `fy` (pixels) are not that of `F` (meters).

So, for any person who knows real cameras, these quantities are meaningless. And, more particularly, they are *derived* from `F`, `sx`, and `sy`. So, for that reason, they shouldn't appear in the public API at all.  Only `F`. I can't imagine that `fx` and `fy` would be *inputs*.


<!-- Sent from Reviewable.io -->

2019-07-17 01:22 UTC, kunimatsu-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-LjxUlZJ-IJmxNUeH8C3:bppo8zv) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

That matlab documentation you link to highlights the ambiguity and confusion. A lens has *a* focal length - a measure from the center of the lens to the focal plane. In the documentation, it is referred to as `F`. But they *also* define `fx` and `fy` as "focal length in x and y". However, the units of `fx` and `fy` (pixels) are not that of `F` (meters).

So, for any person who knows real cameras, these quantities are meaningless. And, more particularly, they are *derived* from `F`, `sx`, and `sy`. So, for that reason, they shouldn't appear in the public API at all.  Only `F`. I can't imagine that `fx` and `fy` would be *inputs*.
</blockquote></details>

FYI, in reality, we have `fx` and `fy` in `pixels` obtained through camera calibration, but don't know what `F`, `sx` and `sy` are. So, I'm ok with having `fx` and `fy`in the public API considering the practical use case.


<!-- Sent from Reviewable.io -->

2019-07-17 02:00 UTC, SeanCurtis-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-LjxeB6u3gG6Lq2HefBc:bbgok4x) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

FYI, in reality, we have `fx` and `fy` in `pixels` obtained through camera calibration, but don't know what `F`, `sx` and `sy` are. So, I'm ok with having `fx` and `fy`in the public API considering the practical use case.
</blockquote></details>

An interesting point -- that suggests that we expect the API to be used primarily via calibration and not via ideal parameterization. That should certainly be captured in the documentation.


<!-- Sent from Reviewable.io -->

2019-07-17 02:01 UTC, SeanCurtis-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-LjxeK7L3zbo5g8eHaUj:bk74yy5) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

An interesting point -- that suggests that we expect the API to be used primarily via calibration and not via ideal parameterization. That should certainly be captured in the documentation.
</blockquote></details>

Either way, calling it "focal length" feels like a horrible lie.


<!-- Sent from Reviewable.io -->

2019-07-17 14:47 UTC, EricCousineau-TRI commented
___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-Lk-OJFQ6n9gj2y8vZhi:busoz89) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Either way, calling it "focal length" feels like a horrible lie.
</blockquote></details>

I would really prefer we stick to what the common convention is, at least for now, especially if we're gearing towards the Computer Vision community.
From what I've done so far, I haven't seen any datasets / code / etc actually use `F, sx, sy`; I've only seen `fx` and `fy`, and it would be bad if we hid those...

I would suggest that we add a comment or something stating that, while these names aren't precise, we keep them for common use with external libraries. Then we can figure out how to better name them, while not disservicing users who are used to those names?


<!-- Sent from Reviewable.io -->

2019-07-17 14:48 UTC, EricCousineau-TRI commented
___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-Lk-OwqE0NI8HwTZsC-a:b-q2z5do) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I would really prefer we stick to what the common convention is, at least for now, especially if we're gearing towards the Computer Vision community.
From what I've done so far, I haven't seen any datasets / code / etc actually use `F, sx, sy`; I've only seen `fx` and `fy`, and it would be bad if we hid those...

I would suggest that we add a comment or something stating that, while these names aren't precise, we keep them for common use with external libraries. Then we can figure out how to better name them, while not disservicing users who are used to those names?
</blockquote></details>

But to your earlier response, yes, we should state that this is geared more towards camera calibration (/ "computer vision", at least as far as I'm familiar with the term...)


<!-- Sent from Reviewable.io -->

2019-07-17 19:54 UTC, EricCousineau-TRI reviewed
Are there any small bits of this that I can continue to refine? Or would you still like to finish out your edits and push 'em here?

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk0UfBm9zeW6dnpvVXZ:bm26aiq)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-17 21:57 UTC, SeanCurtis-TRI requested changes
I've made a big sweeping change -- a philosphical change of direction. Let me know what you think. We can always discard the commit if it's a loser.

> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk0w0y07yefPMuSX0S3:bu36ryt)* status: 5 of 6 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 29 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw6nkS4mi4tJZwI-_V:-Lk-HSiiC73zQxIKiqtv:brbwo8t) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm going to take a stab at this definition:

image plane: a plane perpendicular to the camera's viewing direction on which the image lies.
___
*[systems/sensors/camera_info.h, line 23 at r6](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk-HF7t-u4z1M3NYMM9:-Lk-HF7t-u4z1M3NYMMA:bes5ofl) ([raw file](https://github.com/seancurtis-tri/drake/blob/bd23c1277b9a6bfca9521a7872fa0927f020415c/systems/sensors/camera_info.h#L23)):*
> ```objc
>   frame implies this definition.
> - sensor: a device used to take and report measurements.
> - image: an array of measurements. Coordinates are in typically in pixels.
> ```

nit: "...in typically in..."
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Lk-F7SZ8aF-QoZwDwv_:b-n9u218) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er, meant "minimizing unittest changes"
</blockquote></details>

Not solely -- apparently, that particular configuration has had historic value. It should be labeled, packaged, and made available for general backwards compatibility (rather than a general -- hey, remember how cameras used to work? They don't now. Figure out yourself how to get back to it.)  

You'd previously indicated that those values reflected a particular camera Xtion.  This is just a refactor of that.

Certainly, in order to replace `RgbdCamera` with `RgbdSensor` the built-in behavior of the `RgbdCamera` will have to be replaced with the explicitly configured `RgbdSensor` at *every* call site to maintain current behavior. We certainly don't want to duplicate the same configuration over and over. And it makes more sense to *refactor* in this PR than to simply delete in this PR and add in another.

(Could you tell this was my entire, unordered collection of arguemnts? No particular rhetorical flow. Just my feeling that there are million reasons to do it, and very few reasons to not.)
___
*[systems/sensors/rgbd_sensor.h, line 40 at r6](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk-Gzwd25YQ1O2cFYWo:-Lk-Gzwe-JPZ1_tK2cAL:b-e9ltwo) ([raw file](https://github.com/seancurtis-tri/drake/blob/bd23c1277b9a6bfca9521a7872fa0927f020415c/systems/sensors/rgbd_sensor.h#L40)):*
> ```objc
> 
>  The following text uses terminology and camera frame conventions from
>  %CameraInfo. Please review its documentation.
> ```

*Definitely* remove the `%` from `CameraInfo`. We want this to be a clickable link.


<!-- Sent from Reviewable.io -->

2019-07-17 21:59 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 5 of 6 files reviewed, 18 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 63 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0wWSnDAHANh6hfcai:-Lk0wWSnDAHANh6hfcaj:b-8yjd3u) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L63)):*
> ```objc
>  - (f_x, f_y) defines the model focal length.
> 
>  In other words, for point Q in the world frame, it's texture coordinates
> ```

nit: s/it's/its
___
*[systems/sensors/camera_info.h, line 66 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0wXgQ4b3qZq3LB1D9:-Lk0wXgQ4b3qZq3LB1DA:b-bzkecs) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L66)):*
> ```objc
>  `(uₚ, vₚ)` are calculated as:
> 
>       │ uₚ │
> ```

nit: s/ u_p/u_q


<!-- Sent from Reviewable.io -->

2019-07-17 22:25 UTC, EricCousineau-TRI commented
___
*[systems/sensors/camera_info.h, line 19 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk1-Io_8OhA9ScKTgkE:-Lk1-Io_8OhA9ScKTgkF:b-mrj2it) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L19)):*
> ```objc
>  (which is related to but distinct from an actual
>  [pinhole _camera_](https://en.wikipedia.org/wiki/Pinhole_camera)). The former
>  is a mathematical model for producing images, the latter is a physical object.
> ```

nit minor Can the "(which is ...)" be changed to ", which is ..."? Odd to see "latter" refer to an explicit parenthetical...


<!-- Sent from Reviewable.io -->

2019-07-17 22:25 UTC, EricCousineau-TRI commented
___
*[systems/sensors/camera_info.h, line 50 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0y39x44tgJZxcPZAB:-Lk0y39x44tgJZxcPZAC:bxoutii) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L50)):*
> ```objc
> 
>  %CameraInfo defines the parameters of the intrinsic projection. The projection
>  can be captured by `A`, the camera or intrinsic matrix which essentially maps
> ```

nit Other software docs, papers, etc. tends to use `K`for the intrinsic matrix - can we use that here?


<!-- Sent from Reviewable.io -->

2019-07-17 22:25 UTC, EricCousineau-TRI commented
___
*[systems/sensors/camera_info.h, line 66 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0wXgQ4b3qZq3LB1D9:-Lk0zAEdBdNwK3AjvRnJ:bf2bga5) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: s/ u_p/u_q
</blockquote></details>

Rather than use monogram and Unicode subscripts, can we only use monogram? e.g.
`(u_Q, v_Q)`?
(easier for me to parse)


<!-- Sent from Reviewable.io -->

2019-07-17 22:25 UTC, EricCousineau-TRI reviewed
I like it! Made some nits here and there, and added some more of my own unordered rhetoric on pre-baked intrinsics :P

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk119NCBE6Jp9_YsCNC:b7sn1q8)* status: 5 of 6 files reviewed, 24 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 67 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0yawH4fHrz4Wu8Kdg:-Lk0yawI54X-FJLyZ1iA:b-gx47lj) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L67)):*
> ```objc
> 
>       │ uₚ │
>      s│ vₚ │ = A_C ⋅ X_CW ⋅ p_WQ
> ```

nit `s` is not introduced. Can it somehow be mentioned here?
___
*[systems/sensors/camera_info.h, line 78 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk1-_Sl6J696GCACeBA:-Lk1-_Sl6J696GCACeBB:b-6jbdet) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L78)):*
> ```objc
> 
>  - __aperture__: the opening in a camera through which light passes. The origin
>    of the camera frame is located at the aperture's center.
> ```

nit Can you state `Co` here too?
___
*[systems/sensors/camera_info.h, line 92 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0zUq23O_4IzE1F8YK:-Lk0zUq23O_4IzE1F8YL:b-o3n0yv) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L92)):*
> ```objc
>      where `(s_x, s_y)` are the number of pixels per meter in the x- and
>      y-directions (of the image). Both values described as "focal length" have
>      analogous affects on field of view and scale of objects in the image.
> ```

nit "affects" -> "effects"
___
*[systems/sensors/camera_info.h, line 100 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0zrIL5bKS4rVwc9T9:-Lk0zrIL5bKS4rVwc9TA:bo0vnet) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L100)):*
> ```objc
>  - __image__: an array of measurements such that the measured values have
>    spatial relationships based on where they are in the array.
>  - __image frame__: the 2D frame spanning the image plane. The image frame's
> ```

nit It feels a bit odd to go back towards mixing in "image frame" while using what seems like an arbitrary distinction between 2D and 3D...

I like the definition of "image plane", though. Is it possible to somehow avoid the distinction altogether? Perhaps delete the definition of "image frame", and encode the relation between the image axes and the image plane axes?
___
*[systems/sensors/camera_info.h, line 106 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0ziMz9RZu9Yg35V1U:-Lk0ziMz9RZu9Yg35V1V:b-55i4hj) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L106)):*
> ```objc
>    and `v ≥ 0`).
>  - __image plane__: a plane in 3D which is perpendicular to a camera's viewing
>    direction and positioned "in front" of the camera.
> ```

nit Should we mention the contrasting view, e.g. "behind" for camera obscura?
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Lk1068X4t2a71sPBLeC:b-7oeqh6) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Not solely -- apparently, that particular configuration has had historic value. It should be labeled, packaged, and made available for general backwards compatibility (rather than a general -- hey, remember how cameras used to work? They don't now. Figure out yourself how to get back to it.)  

You'd previously indicated that those values reflected a particular camera Xtion.  This is just a refactor of that.

Certainly, in order to replace `RgbdCamera` with `RgbdSensor` the built-in behavior of the `RgbdCamera` will have to be replaced with the explicitly configured `RgbdSensor` at *every* call site to maintain current behavior. We certainly don't want to duplicate the same configuration over and over. And it makes more sense to *refactor* in this PR than to simply delete in this PR and add in another.

(Could you tell this was my entire, unordered collection of arguemnts? No particular rhetorical flow. Just my feeling that there are million reasons to do it, and very few reasons to not.)
</blockquote></details>

I'm not sure if there was ever a significant reason *why* call sites used that configuration, other than purely that it was (irrevocably) there - I highly doubt most, if any call site, actually cared that it was an Xtion.
To clarify, me adding the `xtion` sensor was kind of a mistake...

What is your concern with changing other call sites?
I'd buy backwards-compatibility if this were not a new class, but it is.

If we *really* want to provide meaningful pre-baked intrinsics, I'd argue we either:
(a) supply something closer to cameras that we care about, e.g. the D415., or
(b) have call sites that *actually* care about it being Xtion pull the values from something like an Xtion-specific header.


<!-- Sent from Reviewable.io -->

2019-07-17 22:27 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 5 of 6 files reviewed, 25 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Lk120Vn3_g2gn-jwMZj:b-mmfsyg) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure if there was ever a significant reason *why* call sites used that configuration, other than purely that it was (irrevocably) there - I highly doubt most, if any call site, actually cared that it was an Xtion.
To clarify, me adding the `xtion` sensor was kind of a mistake...

What is your concern with changing other call sites?
I'd buy backwards-compatibility if this were not a new class, but it is.

If we *really* want to provide meaningful pre-baked intrinsics, I'd argue we either:
(a) supply something closer to cameras that we care about, e.g. the D415., or
(b) have call sites that *actually* care about it being Xtion pull the values from something like an Xtion-specific header.
</blockquote></details>

(I'd be willing to get some sort of "average" D415 intrinsics.)


<!-- Sent from Reviewable.io -->

2019-07-18 14:17 UTC, thduynguyen reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 5 of 6 files reviewed, 26 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-Lk4OJjS6-5YsvsoqAHZ:b-gsfuoa) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

But to your earlier response, yes, we should state that this is geared more towards camera calibration (/ "computer vision", at least as far as I'm familiar with the term...)
</blockquote></details>

`fx` and `fy` are really focal length in terms of __pixels__, related to the focal length `f` in terms of distance via scale factors. See: https://en.wikipedia.org/wiki/Camera_resectioning#Intrinsic_parameters
___
*[systems/sensors/camera_info.h, line 34 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4L1yi8T7PfkQSIwGu:-Lk4L1yi8T7PfkQSIwGv:b-uvr56x) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L34)):*
> ```objc
>  model serves as a camera for a virtually modeled environment. Its parameters
>  are those required to determine where in the resultant image a virtual object
>  appears. In essence, the parameters of the the camera model define a mapping
> ```

nit, extra `the`


<!-- Sent from Reviewable.io -->

2019-07-18 15:02 UTC, thduynguyen reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 5 of 6 files reviewed, 26 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 117 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4_jPh9QKgj-YYuBWr:-Lk4_jPh9QKgj-YYuBWs:bt0kuj0) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L117)):*
> ```objc
>  produced it, one can say that Cz points into the image, Cx is parallel with the
>  image rows, pointing to the right, and Cy is parallel with the image columns,
>  pointing down leading to language such as: "X-right", "Y-down", and "Z-forward".
> ```

BTW, I respect our wish/tendency to be very rigorous, but it seems like we are trying to write a textbook and I'm not sure if it's worth doing and/or healthy. We are *not* saying anything new nor clarifying any confusion there. Computer vision people will regard those as known and don't look at it. If they do, like me, they would just be more confused. :slightly_smiling_face: Several terms, e.g. `imager`, are defined but not used elsewhere. Non-computer vision people should just find a proper book to read if they don't have those basic background/terminologies instead of reading these. We should just refer to  standard text, if not wikipedia, for example, chapter 6 in this well-known book, standard in computer vision: https://www.amazon.com/Multiple-View-Geometry-Computer-Vision-ebook/dp/B00AKE1QK4 , then clarify how our terminologies/terms are different.

I'm ok for leaving them as is. Feel like I should voice up as I'm kind of scared if we have to write these kinds of basic docs for every piece of code we write.


<!-- Sent from Reviewable.io -->

2019-07-18 15:13 UTC, SeanCurtis-TRI requested changes
Comments addressed (feels like we're getting close).

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk4d6ys2DJEWnq10-3g:bciqd63)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, @SeanCurtis-TRI, and @thduynguyen)

___
*[systems/sensors/camera_info.h, line 58 at r5](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Ljw9bPc6SatB6GNfEEj:-Lk4ZDjbC3MNAVvMRk5q:b-kgslry) ([raw file](https://github.com/seancurtis-tri/drake/blob/96fd4d9b50aef0f479464841c13437962fb95d71/systems/sensors/camera_info.h#L58)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

`fx` and `fy` are really focal length in terms of __pixels__, related to the focal length `f` in terms of distance via scale factors. See: https://en.wikipedia.org/wiki/Camera_resectioning#Intrinsic_parameters
</blockquote></details>

While I can accept that's true in the strictest definition (.e., f_x = F * s_x) where iF is in meters, s_x is pixels/meter, therefore f_x is F with a unit change into pixels.  However, it's the s_x (and s_y) terms that cause me to balk. A real lens's focal length is not dependent on the "resolution" of the imaging surface. And, given that we typically use radially symmetric lenses, a single scalar is sufficient. So, I more fully subscribe to the statement in the wikipedia that the intrinsic matrix's parameters "__encompass__ focal_length, ...", it still grates on my nerves to call both `F` *and* `(f_x, f_y)` *and* `f_x` and `f_y`, individually, "focal length".

Most importantly, take a look at the new glossary term for "focal length" and confirm that I'm still true to the convention.
___
*[systems/sensors/camera_info.h, line 19 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk1-Io_8OhA9ScKTgkE:-Lk4SILdERI0NoDgnfQ_:bb6un1j) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit minor Can the "(which is ...)" be changed to ", which is ..."? Odd to see "latter" refer to an explicit parenthetical...
</blockquote></details>

Done
___
*[systems/sensors/camera_info.h, line 34 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4L1yi8T7PfkQSIwGu:-Lk4SKzF1p3VNkD07V-M:bk7wfzi) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L34)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

nit, extra `the`
</blockquote></details>

Done (Maybe I really wanted to emphasize how *definite* the article is. :))
___
*[systems/sensors/camera_info.h, line 50 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0y39x44tgJZxcPZAB:-Lk4SQTL6Y9myqXLpqvf:b-nmikc5) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Other software docs, papers, etc. tends to use `K`for the intrinsic matrix - can we use that here?
</blockquote></details>

Done Take a look at my compromise.
___
*[systems/sensors/camera_info.h, line 63 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0wWSnDAHANh6hfcai:-Lk4T3z_9dErAFKnPbmb:bb6un1j) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L63)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: s/it's/its
</blockquote></details>

Done
___
*[systems/sensors/camera_info.h, line 66 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0wXgQ4b3qZq3LB1D9:-Lk4T4ni02Dd9cvEyEOo:bb6un1j) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Rather than use monogram and Unicode subscripts, can we only use monogram? e.g.
`(u_Q, v_Q)`?
(easier for me to parse)
</blockquote></details>

Done
___
*[systems/sensors/camera_info.h, line 67 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0yawH4fHrz4Wu8Kdg:-Lk4TlZI2_j7QMRmRfV-:b-3jvqoz) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `s` is not introduced. Can it somehow be mentioned here?
</blockquote></details>

Done I've taken a stab at doing it, balancing completeness with *not* turning into Homogeneous Coordinates 101. PTAL.
___
*[systems/sensors/camera_info.h, line 78 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk1-_Sl6J696GCACeBA:-Lk4_OfD2wgswrnLnhC_:bb6un1j) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L78)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you state `Co` here too?
</blockquote></details>

Done
___
*[systems/sensors/camera_info.h, line 92 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0zUq23O_4IzE1F8YK:-Lk4_T0eEMwOgiCgRbTu:b-gswlry) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L92)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "affects" -> "effects"
</blockquote></details>

Done (good catch)
___
*[systems/sensors/camera_info.h, line 100 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0zrIL5bKS4rVwc9T9:-Lk4_l-AD7gmZuskSP1I:b-520bao) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It feels a bit odd to go back towards mixing in "image frame" while using what seems like an arbitrary distinction between 2D and 3D...

I like the definition of "image plane", though. Is it possible to somehow avoid the distinction altogether? Perhaps delete the definition of "image frame", and encode the relation between the image axes and the image plane axes?
</blockquote></details>

Hmmm... lots to unpack.

- You'll note I no longer deal with a 2D *and* a 3D image frame. :)
- I don't understand the "mixing" to which you are referring. Can you elaborate?
- definition of image plane: it's important to define this because it's part of the definition of focal length. (At least I *think* it's important...)
- I think we need the frame because "image axes" and "plane axes" are ill-defined. You can suggest the former is row direction and column direction, but planes don't implicitly have axes. You must have a frame.

Conclusion: If you can point more directly to a problem, I can try to alleviate it, otherwise I'm inclined to let it go as is.
___
*[systems/sensors/camera_info.h, line 106 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0ziMz9RZu9Yg35V1U:-Lk4ao0R5EOz-Ew1Evnj:b-884au) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L106)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should we mention the contrasting view, e.g. "behind" for camera obscura?
</blockquote></details>

Done (that one slipped between the cracks).
___
*[systems/sensors/camera_info.h, line 117 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4_jPh9QKgj-YYuBWr:-Lk4bGGX1UhGqsBp3a_E:b-wyqm4u) ([raw file](https:/ [...]

2019-07-18 15:14 UTC, SeanCurtis-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, @SeanCurtis-TRI, and @thduynguyen)

*[a discussion](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4dMui68F5OHcOiOqr:-Lk4dMuj1kFSIYJbOJIV:b64bev7) (no related file):*
@thduynguyen What would you advocate the documentation should look like? I'm sympathetic with your point and if we can accomplish the same end with less text, I love it.

---


<!-- Sent from Reviewable.io -->

2019-07-18 15:24 UTC, SeanCurtis-TRI reviewed
Oops...some additional tweaks to the constructor documentation -- aligning nomenclature to be consistent and to remove otherwise unused text.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk4fejK32ED0hCrHCpl:b-nfccab)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, @SeanCurtis-TRI, and @thduynguyen)



<!-- Sent from Reviewable.io -->

2019-07-18 15:27 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, @SeanCurtis-TRI, and @thduynguyen)

___
*[systems/sensors/camera_info.h, line 48 at r4](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LjvsoQF-yVBIMWXHmJD:-Lk4fpYQ3Q_pUuZftk40:bs3z66a) ([raw file](https://github.com/seancurtis-tri/drake/blob/28253c01e3c3354b49002f47432eb2507c32d1a6/systems/sensors/camera_info.h#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I can't think of a better way to be explicit; can I ask if you have any suggestions?
</blockquote></details>

Yep -- a whole bunch of new text as my suggestion.  :)


<!-- Sent from Reviewable.io -->

2019-07-18 16:45 UTC, thduynguyen reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, @SeanCurtis-TRI, and @thduynguyen)

___
*[systems/sensors/camera_info.h, line 117 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4_jPh9QKgj-YYuBWr:-Lk4fQ313V-mKYV9vyAy:b-4xle27) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L117)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I would argue your audience is more than computer vision people. I come from a rendering background and much of this was unfamiliar (they are, after all, inverse problems). As such, enough of a manual to provide context for our parameters such that anyone who thinks they understand physical cameras can *still* understand cameras in Drake feels important.

And I appreciate you being willing to go along for the ride.
</blockquote></details>

IMO, we can't assume a common background for all people, but code documentation is not supposed to be a textbook. This doc satisfies your need but I'm sure there is a non-empty set of people who don't fully understand this doc as they lack sufficient knowledge. Even in your comment, the assumption is that the audience should understand physical cameras. I'm not sure if that's a valid or "clear enough" assumption, and even if it is, there is an implicit assumption about the level understanding that is not stated.

So I think the most rigorous way is to refer to a standard reference, which btw could be our own book or more detail rigorous docs, and just clarify the differences or high-level ideas here as code documentation. If one doesn't have sufficient background, there are many ways to learn that background to satisfy one's needs. I don't think code documentation is the way as its scope is too limited for that purpose. The best we could and should do is to leave a high-level intro and pointers to where that knowledge can be obtained.

For this class, in particular, the variables `fx`, `fy`, `cx`, `cy`, and the `intrinsic_matrix` are all defined in the standard reference book I cited above. The "rigorous me" to satisfy a very rigorous reviewer like you (in a good sense) would say something like: `This class captures the CCD camera model as defined in [HartleyZisseman03], chapter 6.`, then put a short explanation for each variable, e.g. `focal_x: The focal length of the camera in terms of pixel dimensions in the x direction`, or the `intrinsic_matrix` is just the equation (6.9) in the book. It's hard to find a better reference than that book. My "normal me" would just refer to a wikipedia or opencv link and assume users are able to start from there to get the knowledge however they want, but I don't think that meets your standard of rigor.

Btw, I'm not actually willing to go along for the ride as English wording is not my strength. It takes me an hour to respond to your 5-min comment. :) I recommend we leave the current doc as it is. I actually think it's very good thank to your help.


<!-- Sent from Reviewable.io -->

2019-07-18 17:20 UTC, sherm1 reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI, @kunimatsu-tri, @SeanCurtis-TRI, and @thduynguyen)

___
*[systems/sensors/camera_info.h, line 117 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4_jPh9QKgj-YYuBWr:-Lk54srw4Cw1hBY3DH5m:b-5blnth) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L117)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

IMO, we can't assume a common background for all people, but code documentation is not supposed to be a textbook. This doc satisfies your need but I'm sure there is a non-empty set of people who don't fully understand this doc as they lack sufficient knowledge. Even in your comment, the assumption is that the audience should understand physical cameras. I'm not sure if that's a valid or "clear enough" assumption, and even if it is, there is an implicit assumption about the level understanding that is not stated.

So I think the most rigorous way is to refer to a standard reference, which btw could be our own book or more detail rigorous docs, and just clarify the differences or high-level ideas here as code documentation. If one doesn't have sufficient background, there are many ways to learn that background to satisfy one's needs. I don't think code documentation is the way as its scope is too limited for that purpose. The best we could and should do is to leave a high-level intro and pointers to where that knowledge can be obtained.

For this class, in particular, the variables `fx`, `fy`, `cx`, `cy`, and the `intrinsic_matrix` are all defined in the standard reference book I cited above. The "rigorous me" to satisfy a very rigorous reviewer like you (in a good sense) would say something like: `This class captures the CCD camera model as defined in [HartleyZisseman03], chapter 6.`, then put a short explanation for each variable, e.g. `focal_x: The focal length of the camera in terms of pixel dimensions in the x direction`, or the `intrinsic_matrix` is just the equation (6.9) in the book. It's hard to find a better reference than that book. My "normal me" would just refer to a wikipedia or opencv link and assume users are able to start from there to get the knowledge however they want, but I don't think that meets your standard of rigor.

Btw, I'm not actually willing to go along for the ride as English wording is not my strength. It takes me an hour to respond to your 5-min comment. :) I recommend we leave the current doc as it is. I actually think it's very good thank to your help.
</blockquote></details>

BTW I ordered the Hartley & Zisserman so we'll have a copy in the Dynamics & Simulation library at HQ.


<!-- Sent from Reviewable.io -->

2019-07-18 17:23 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 117 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk4_jPh9QKgj-YYuBWr:-Lk55tcL4dkgzHyIqEOc:b-e6a1fc) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L117)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I ordered the Hartley & Zisserman so we'll have a copy in the Dynamics & Simulation library at HQ.
</blockquote></details>

Fair enough, thanks @thduynguyen. 


<!-- Sent from Reviewable.io -->

2019-07-18 19:56 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 66 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0wXgQ4b3qZq3LB1D9:-Lk52tCE8R8Fimp0xn9N:b-9icd4y) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done
</blockquote></details>

BTW Would still be nice to have `u_Q, v_Q` rather than `u_q, v_q` for full parity, but eh.
___
*[systems/sensors/camera_info.h, line 100 at r7](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk0zrIL5bKS4rVwc9T9:-Lk5ck2WDiO5wPdd9zGs:b-ph10fq) ([raw file](https://github.com/seancurtis-tri/drake/blob/5f78508b3f873fce09c423e4ab4e4ff11f54d170/systems/sensors/camera_info.h#L100)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Hmmm... lots to unpack.

- You'll note I no longer deal with a 2D *and* a 3D image frame. :)
- I don't understand the "mixing" to which you are referring. Can you elaborate?
- definition of image plane: it's important to define this because it's part of the definition of focal length. (At least I *think* it's important...)
- I think we need the frame because "image axes" and "plane axes" are ill-defined. You can suggest the former is row direction and column direction, but planes don't implicitly have axes. You must have a frame.

Conclusion: If you can point more directly to a problem, I can try to alleviate it, otherwise I'm inclined to let it go as is.
</blockquote></details>

OK The update of "2D in 3D" improves things. I think mayhaps we keep this as-is, and I take the initiative to resolve as a follow-up?
___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Lk5d8Sp9rqUVukF9voi:b-b8v3wn) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
> Would you characterize that as "average" or "idealized"?

Probably idealized at this point, given that we don't support `ppx != width / 2`.

> [...] So, to maintain the same functionality, the RgbdCamera they currently use should be replaced with an equivalent RgbdSensor. [...]

I would prefer that we introduce the numbers when they're used. This PR doesn't seem to migrate anything, so I think the *single* unittest should contain the "whatever" intrinsics+extrinsics. Then, when migration actually happens, we figure out where to introduce it?
(I think we're arguing too much in the abstract... sorry about that!)


<!-- Sent from Reviewable.io -->

2019-07-18 19:57 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[systems/sensors/rgbd_sensor.h, line 240 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LiEx6Iq-oTmHpj9u7EH:-Lk5eCMzBOiPOLn8qsLq:b7aqdla) ([raw file](https://github.com/seancurtis-tri/drake/blob/4c65f16a53352847385f118332801a9ea624abf9/systems/sensors/rgbd_sensor.h#L240)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> Would you characterize that as "average" or "idealized"?

Probably idealized at this point, given that we don't support `ppx != width / 2`.

> [...] So, to maintain the same functionality, the RgbdCamera they currently use should be replaced with an equivalent RgbdSensor. [...]

I would prefer that we introduce the numbers when they're used. This PR doesn't seem to migrate anything, so I think the *single* unittest should contain the "whatever" intrinsics+extrinsics. Then, when migration actually happens, we figure out where to introduce it?
(I think we're arguing too much in the abstract... sorry about that!)
</blockquote></details>

(where to introduce it to prevent copy pasta when it's semantically useful)


<!-- Sent from Reviewable.io -->

2019-07-18 20:08 UTC, kunimatsu-tri commented
___
*[systems/sensors/camera_info.h, line 153 at r9](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk5gMqv5r0tx1MaNRVu:-Lk5gMqv5r0tx1MaNRVv:b-s07xb7) ([raw file](https://github.com/seancurtis-tri/drake/blob/2cbaa29d73a9dbd26767c43933e8a4c15677cbb2/systems/sensors/camera_info.h#L153)):*
> ```objc
>    Constructs this instance from image size and vertical field of view. We
>    assume the principal point is in the center of the image;
>    `(center x, center_y)` is equal to `(width / 2, height / 2)`. We also assume
> ```

Oops, can you replace this part with `is equal to (width / 2 - 0.5, height / 2 - 0.5)` as this is how it is:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/camera_info.cc#L27

This is my bad not modifying the doc correctly when I fixed the offset.


<!-- Sent from Reviewable.io -->

2019-07-18 21:10 UTC, SeanCurtis-TRI reviewed
@ericcousineau-tri, I would like to lob this back to you. GIven that you took the liberty of changing the semantics, I'd like you to take the responsiblity to make the unit test pass.  :)  At the same time, if you could hit the `u_q`/`u_Q` thing and the `center_x = width_x / 2 + 0.5` that Kuni called out, I'd appreciate it. Right now I've up to my elbows in something and won't be able to get back to this PR until tomorrow.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk5uaC84xykzTsUymau:b-xv3hpl)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-18 23:55 UTC, EricCousineau-TRI reviewed
Sounds good!

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk6Vjqn8I65hVCMJcCP:brxp9sd)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-19 00:45 UTC, EricCousineau-TRI reviewed
Done. Did those changes, as well:
* Removed "name". It's the System's responsibility, and there's no reason to require (that I'm aware of it). Having written some 6d labels before with `attic`s RgbdCamera, I disliked having to provide unique information that I had no use for.
* Removed the TODO about the target-position-up constructor... That doesn't really make sense to me if we're simulating a physical system. It would make more sense to have some auxillary "camera-man" frame controller that handles that, rather than try to imbue that in `RgbdSensor` as a visualization camera? (I can put it back, though)

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk6fcmC4wgH-NLQvZS4:b-df2tv3)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 153 at r9](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk5gMqv5r0tx1MaNRVu:-Lk6fXwuBBDauXB1_t5b:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/2cbaa29d73a9dbd26767c43933e8a4c15677cbb2/systems/sensors/camera_info.h#L153)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Oops, can you replace this part with `is equal to (width / 2 - 0.5, height / 2 - 0.5)` as this is how it is:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/camera_info.cc#L27

This is my bad not modifying the doc correctly when I fixed the offset.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-19 01:00 UTC, EricCousineau-TRI reviewed
(For the target-position-up, I'm fine with their being an issue that describes the workflow in more detail, but I think a TODO here is a wee bit confusing)

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk6jNUK9p2xCyDoc2jB:b-qke4eb)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri and @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-19 01:05 UTC, EricCousineau-TRI reviewed
Confirmed that `bazel test ...` passed on my machine (after having to clean out my bazel cache cobwebs)

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-Lk6ko0u6nna0OIaL1Z8:bhv2aza)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri and @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-19 17:50 UTC, SeanCurtis-TRI approved these changes
Thanks a million, @ericcousineau-tri. I've made a few last tweaks, ptal. 

> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LkALrZaC20BD4Aaetqm:b-wqmpmj)* status: all files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)

___
*[systems/sensors/camera_info.h, line 153 at r9](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk5gMqv5r0tx1MaNRVu:-LkALWkd9jH6sBtBYfjM:b-egmixr) ([raw file](https://github.com/seancurtis-tri/drake/blob/2cbaa29d73a9dbd26767c43933e8a4c15677cbb2/systems/sensors/camera_info.h#L153)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@kunimatsu-tri I'd like to add a comment to the code about *why* the 0.5 is necessary. Could you state that reason so I can include it?
___
*[systems/sensors/test/rgbd_sensor_test.cc, line 154 at r10](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LkAK41Y9ESJ-qnAwFJ6:-LkAK41Y9ESJ-qnAwFJ7:b-z87hmh) ([raw file](https://github.com/seancurtis-tri/drake/blob/1304296182c477fc033534beea381d5d22c654e4/systems/sensors/test/rgbd_sensor_test.cc#L154)):*
> ```cpp
>     // TODO(eric.cousineau): Remove the name tests, as they don't make sense
>     // since no part of RgbdSensor part really needs it, and it's the System
>     // framework's responsibility.
> ```

BTW I'm just removing it.
___
*[systems/sensors/rgbd_sensor.h, line 120 at r10](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk6qkU29Gv01jTOXuV0:-Lk6qkU29Gv01jTOXuV1:b-4hjatd) ([raw file](https://github.com/seancurtis-tri/drake/blob/1304296182c477fc033534beea381d5d22c654e4/systems/sensors/rgbd_sensor.h#L120)):*
> ```objc
>              bool show_window = false);
> 
>   // TODO(eric.cousineau): Add a constructor that allows unique intrinsics for
> ```

BTW As a TODO this isn't very helpful. It essentially says "Do stuff when it needs to be done." It doesn't enumerate a particular task. I've removed it.


<!-- Sent from Reviewable.io -->

2019-07-19 18:00 UTC, SeanCurtis-TRI approved these changes
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: all files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)



<!-- Sent from Reviewable.io -->

2019-07-19 18:28 UTC, EricCousineau-TRI reviewed
Sweet!

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LkAUXO17DnJzOGnfIDo:bzftu3a)* status: all files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)

___
*[systems/sensors/test/rgbd_sensor_test.cc, line 154 at r10](https://reviewable.io/reviews/seancurtis-tri/drake/5#-LkAK41Y9ESJ-qnAwFJ6:-LkAUTiQBW5ZRfSOyyV8:bfiuedt) ([raw file](https://github.com/seancurtis-tri/drake/blob/1304296182c477fc033534beea381d5d22c654e4/systems/sensors/test/rgbd_sensor_test.cc#L154)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm just removing it.
</blockquote></details>

OK Woohoo!
___
*[systems/sensors/rgbd_sensor.h, line 120 at r10](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk6qkU29Gv01jTOXuV0:-LkAUOcf1Ii8T8dZAYJu:b6x1lnh) ([raw file](https://github.com/seancurtis-tri/drake/blob/1304296182c477fc033534beea381d5d22c654e4/systems/sensors/rgbd_sensor.h#L120)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As a TODO this isn't very helpful. It essentially says "Do stuff when it needs to be done." It doesn't enumerate a particular task. I've removed it.
</blockquote></details>

OK Sounds good! Will file an issue to try and expand on the workflow.


<!-- Sent from Reviewable.io -->

2019-07-19 18:29 UTC, SeanCurtis-TRI approved these changes
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: all files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)



<!-- Sent from Reviewable.io -->

2019-07-19 19:42 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: all files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)

___
*[systems/sensors/camera_info.h, line 153 at r9](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk5gMqv5r0tx1MaNRVu:-LkAjniZ-ibqn9aR9Al9:b-8keoq0) ([raw file](https://github.com/seancurtis-tri/drake/blob/2cbaa29d73a9dbd26767c43933e8a4c15677cbb2/systems/sensors/camera_info.h#L153)):*
Scribing f2f, it supports half-pixel coordinates as discussed in item (2) here:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_fragment_coord_conventions.txt

To (attempt to) show it in pictures for a 2x2 and a 3x3 image, sketching it out in Inkscape:
> ![opengl_pixel_coordinates.svg.png](https://files.reviewableusercontent.io/images/reviewable/26719449/sTwm1rmgK1_mnLpYTO6jLiID/opengl_pixel_coordinates.svg.png)

Does this help?


<!-- Sent from Reviewable.io -->

2019-07-19 19:55 UTC, kunimatsu-tri commented
___
*[systems/sensors/camera_info.h, line 153 at r9](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk5gMqv5r0tx1MaNRVu:-LkAeORn3ZcgCeHN4rUW:beg3mqw) ([raw file](https://github.com/seancurtis-tri/drake/blob/2cbaa29d73a9dbd26767c43933e8a4c15677cbb2/systems/sensors/camera_info.h#L153)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Scribing f2f, it supports half-pixel coordinates as discussed in item (2) here:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_fragment_coord_conventions.txt

To (attempt to) show it in pictures for a 2x2 and a 3x3 image, sketching it out in Inkscape:
> ![opengl_pixel_coordinates.svg.png](https://files.reviewableusercontent.io/images/reviewable/26719449/sTwm1rmgK1_mnLpYTO6jLiID/opengl_pixel_coordinates.svg.png)

Does this help?
</blockquote></details>

Just to back @ericcousineau-tri up, here is the thing we care in the link: 
```
OpenGL assumes a lower-left origin for window coordinates and assumes pixel centers are
located at half-pixel coordinates. This means the XY location (0.5,0.5) corresponds to
the lower-left-most pixel in a window.
```
Note that we use `image frame` instead of `window coordinates` and the origin is top-left instead of lower-left.

`OpenCV` also follows this convention. 


<!-- Sent from Reviewable.io -->

2019-07-19 21:59 UTC, SeanCurtis-TRI approved these changes
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: all files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri)

___
*[systems/sensors/camera_info.h, line 153 at r9](https://reviewable.io/reviews/seancurtis-tri/drake/5#-Lk5gMqv5r0tx1MaNRVu:-LkApsz2AEahjONC4bpJ:b-1cw4sl) ([raw file](https://github.com/seancurtis-tri/drake/blob/2cbaa29d73a9dbd26767c43933e8a4c15677cbb2/systems/sensors/camera_info.h#L153)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Just to back @ericcousineau-tri up, here is the thing we care in the link: 
```
OpenGL assumes a lower-left origin for window coordinates and assumes pixel centers are
located at half-pixel coordinates. This means the XY location (0.5,0.5) corresponds to
the lower-left-most pixel in a window.
```
Note that we use `image frame` instead of `window coordinates` and the origin is top-left instead of lower-left.

`OpenCV` also follows this convention. 
</blockquote></details>

I really appreciate the info/insight, but, to be perfectly frank, I'm not entirely sure how to capture this in the code such that a future reader can understand this.

### Basic concern

This seems to be tying `CameraInfo` to OpenGL.  (Particularly if I provide that link for the justification). Certainly, tying it to OpenGL seems to tie it to a number of other APIs as well which helps soften the concern. However, even with that softening, it feels like this "concept" of principal point is now overly conflated with implementation -- shouldn't it be modified by classes that *consume* `CameraInfo` and know that they are subject to this convention? Is there a way to discuss this without implying we've coupled this class to OpenGL conventions?

### Random way to think about this

So, the statement that the image lies "entirely" in the first quadrant of the image frame is a lie (there is a half-pixel wide strip spilling over the first quadrant's boundary). This arises from two things:

  1. (r, c) as a pixel identify should map to the pixel's center.
  2. When we map (r, c) to (u, v), we want u and v to be whole numbers.

This is only possible if the image is positioned such that the image frame origin is in the center of the (r=0, c=0) pixel.

Thoughts?

### What would the monogram notation for the principal point be?

Let's say we have two frames: frame `I` is the frame illustrated in the diagram above and documented as "image frame". frame `M` is a frame that is aligned with `I`, but positioned such that the image lies entirely in the quadrant. I.e., `X_IM` = Translation(-0.5, -0.5)`. So, if I call the principal point, P, `p_MP = (width / 2, height / 2)` and `p_IP = X_IM * p_MP`.

And if I provide a (u, v) point to look up in the image, what frame is that expressed in?  I.

### Summary

I still have no clue what to write about this (-0.5, -0.5) offset in the code. In the short-term, I've put a TODO in with the link. If you can come up with some meaningful text to replace the todo, then huzzah!


<!-- Sent from Reviewable.io -->

2019-07-19 22:16 UTC, SeanCurtis-TRI reviewed
> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @kunimatsu-tri and @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-19 22:17 UTC, SeanCurtis-TRI reviewed
BTW I'm going to merge this into the main PR as is (just so I meet my own Friday deadline). We'll have a chance to quibble there (https://reviewable.io/reviews/RobotLocomotion/drake/11704).

> Dismissed @kunimatsu-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5#-:-LkBIt08C6c-cZyk4Ob8:b-2lqhcn)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2019-07-19 22:18 UTC, SeanCurtis-TRI approved these changes
> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/5)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-07-19 22:18 UTC, merged